### ISSUE TITLE
[Bug] Same "random" Posting address for every posting job in "Monitor folder" mode

### ISSUE THREAD

**Issue by Tensai75** [mbruel/ngPost#25]
Hi,

when the automatic "Monitor folder" mode is used (which I love btw), the randomly generated Poster address is the same for all posting jobs.

Steps to reproduce:
1. configure ngPost to use random Poster address
2. start ngPost with "--monitor" option
3. add several folders (or files) to the monitored folder
4. for each file or folder a NZB file will be generetad showing the same Poster address

ngPost should however generate a true random Poster address for every different upload.

Thanks and best regards

**Comment by mbruel** [comment]
hum true...
I guess I could add a --gen_from command cause maybe some people would like that behaviour...
not sure when I'll have time for this...

**Comment by mbruel** [comment]
I've implemented it.
in command line you have the new --gen_from option.
in the config file the GEN_FROM keyword.
```
## Generate new random poster for each post (--auto or --monitor)
#GEN_FROM = true
```
and there is a new checkbox in the .

What OS do you use? Do you need me to build it for you? I'm not releasing the v4.5 yet as I'm planing to add another feature.

feel free to give a small [contribution to reward the support](https://github.com/mbruel/ngPost#donations) ;)
Cheers!

**Comment by Tensai75** [comment]
Hi Matthieu

Many thanks. Can you build a Win10 version for me to testing it beforehand?
I have also sent out some bitcoins to your wallet.
Keep up the good work. Was about time for such a new uploading tool.

Best regards!

**Comment by mbruel** [comment]
Hi,

[here is a win64 build](https://files.fm/u/64h87qnh).
It's the exe only, just replace the one you have in your ngPost installation folder.
Run it with the GUI, you should see the "new email for each Post" checkbox on the top right. Select it. Save. Check your config file, it should have been updated with the GEN_FROM keyword ;)
Then give it a try either with the monitoring or post generation feature ;)

Thanks for the coins, really appreciated ;)

Yeah was quite a long time I was thinking to create my own soft as all the existing ones where not so handy to use and sometime to install too...

Let me know if all is working as expected. If so, please close the issue.
Have a good day!

**Comment by Tensai75** [comment]
Hi Matthieu

thanks for the build.
The config file was updated with the GEN_FROM keyword and the new feature works as intended as long as you manually edit the config file and comment out the FROM keyword.

Obviously the  "FROM" keyword has precedence over the GEN_FROM keyword. At least in my tests the GEN_FROM keyword is ignored even if set to true as long as the FROM keyword is set.
But the GUI does not seem to comment out the FROM keyword if the "new email for every post" box is ticked and the config saved. So with the GUI the same address as set in the FROM keyword is still used for every upload even if the box is ticked.

Steps to reproduce:
- open GUI
- untick the "new email for every post" checkbox
- Set "Poster" field to any address or use the "generate random Poster" to generate a random address
- click the save config button
- check the ngPost.conf file --> the FROM keyword is set to the Poster address
- in the GUI now tick the "new email for every post" checkbox
- click the save config button
- start monitoring a folder for automatic upload and add some files/folder to the monitored folder

Expected behaviour:
- the FROM keyword in the ngPost.conf file should be commented out.
- the files/folders should be uploaded with different Poster address for every upload

Actual behaviour:
- the FROM keyword in the ngPost.conf file is not commented out.
- the files/folders are all uploaded with the same Poster address as set with the FROM keyword.

Best regards, Michael

**Comment by mbruel** [comment]
Hi,
my bad, I forgot to connect the GUI "new email for each Post" checkbox to the code, so only the configuration file was working...

I've corrected that and added a new "always" checkbox. Plus now the GEN_FROM will always win.
Here are the 4 possible cases:

1.: FROM is commented / GEN_FROM is commented (or not true)
=> an random email will be generated AND will be used for all the Posts of this current instance of the App (meaning, next time you launch ngPost, you'll get another random email)
On the GUI the "always" checkbox will be checked

2.:  FROM is NOT commented / GEN_FROM is commented (or not true)
we will use the email provided.

3.: FROM is commented / GEN_FROM is NOT commented (and set to yes on or true)
GEN_FROM wins => FROM will be ignored, we will always generate a new random email for each post.

4.:  FROM is NOT commented / GEN_FROM is NOT commented (and set to yes on or true)
GEN_FROM wins => FROM will be ignored, we will always generate a new random email for each post.

Please let me know what you think of that and if it is working as expected.
Cheers!

PS: [here is the win64 build](https://files.fm/u/zqa797cs)

**Comment by Tensai75** [comment]
Hi Matthieu

Working like a charm now. The behaviour of the FROM and GEN_FROM keywords is now as I would expect and I also like that GEN_FROM has now precedence.
However, the GUI settings are not very intiutive to me and maybe also other users. It think it would be more clear to have selectboxes instead of checkboxes:

![image](https://user-images.githubusercontent.com/34959627/77249888-84cfac80-6c44-11ea-853c-ef391993964d.png)

1. option selected: Input field is active / FROM is NOT commented and set to the value of the imput field / GEN_FROM is commented (or not true)
2. option selected: Input field is inactive / FROM is commented / GEN_FROM is commented (or not true)
3. option selected: Input field is inactive / FROM is commented / GEN_FROM is NOT commented (and set to yes on or true)

Regards, Tensai

**Comment by mbruel** [comment]
well if you don't use GEN_FROM, but use a random FROM (meaning in the config file both FROM and GEN_FROM) are commented), I like the idea that you can see what will be used and allow the user to customize it if he wishes.
So the radio buttons would not allow that.
I've made a small update to deactivate also the "always" checkbox when "new email for each post" is checked. Would this make more sense?
There is a tooltip on the "always" checkbox explaining what it does.

**Comment by Tensai75** [comment]
Well, honestly I still don't see a usecase for this "random address per session" anyway. The posters I know will either use a fixed address or a random address for each post. And if they use a random address, they don't care to see what random address is used and certainly don't want to change or customize it. Especially if it is only valid for the current session.

So personally, I still think two simple options (a fix address or random address for each post) are acctually sufficient.

But anyway, I would then suggest to rename "always" to "generate new poster email at every startup of ngPost" and invert the function:

![image](https://user-images.githubusercontent.com/34959627/77252360-a71cf680-6c53-11ea-836f-f8cc9ef190d7.png)
1. both checkboxes are unchecked: input field shows the FROM value / FROM is NOT commented and set to the value of the imput field if settings are saved / GEN_FROM is commented (or not true)
2. first checkbox is checked: second checkbox is unchecked / input field shows the randomly generated email for this session / FROM is commented / GEN_FROM is commented (or not true)
3. second checkbox is checked: first checkbox is unchecked / input field is disabled / FROM is commented / GEN_FROM is NOT commented (and set to yes on or true)

Regards, Tensai

**Comment by mbruel** [comment]
I don't know what users can do...
It could make sense to use a same poster email to upload the whole season of TV show? or all the books of an author?
In that case you would like a random email but why not customize it to describe the post...
This is more for casual posters.
Having the same poster for all the individual posts of a session could allow a fast search in public indexers like binsearch.
No clue if it will be used...
But I guess it doesn't bother most people that would have the GEN_FROM on ;)

**Comment by Tensai75** [comment]
Well, Ok, there might actually be some exceptional usecases for this nevertheless.
Anyway, I will now close this issue as it has been resolved. And I am sure you will find a proper way to present the the settings in the GUI ;-)

Thanks again and keep up the work!

Tensai
